import { daysAgo, daysFromNow, SEED_IDS } from "./ids";

export const EXTRA_REP_EMAILS = {
  sam: "sam.patel@gushwork.demo",
  riley: "riley.chen@gushwork.demo",
} as const;

export const EXTRA_IDS = {
  prospects: {
    cloudLedger: "11111111-1111-4111-8111-111111111201",
    finStack: "11111111-1111-4111-8111-111111111202",
    payRoute: "11111111-1111-4111-8111-111111111203",
    greenCart: "11111111-1111-4111-8111-111111111211",
    loomWear: "11111111-1111-4111-8111-111111111212",
    petNova: "11111111-1111-4111-8111-111111111213",
    brightDental: "11111111-1111-4111-8111-111111111214",
    apexLegal: "11111111-1111-4111-8111-111111111221",
    harborOps: "11111111-1111-4111-8111-111111111222",
    metricFlow: "11111111-1111-4111-8111-111111111223",
    signalHR: "11111111-1111-4111-8111-111111111224",
  },
  meetings: {
    cloudLedgerDiscovery: "22222222-2222-4222-8222-222222222501",
    cloudLedgerDemo: "22222222-2222-4222-8222-222222222502",
    finStackDiscovery: "22222222-2222-4222-8222-222222222511",
    finStackFollowUp: "22222222-2222-4222-8222-222222222512",
    payRouteDiscovery: "22222222-2222-4222-8222-222222222521",
    payRouteClosing: "22222222-2222-4222-8222-222222222522",
    greenCartDiscovery: "22222222-2222-4222-8222-222222222531",
    loomWearDiscovery: "22222222-2222-4222-8222-222222222541",
    loomWearDemo: "22222222-2222-4222-8222-222222222542",
    petNovaDiscovery: "22222222-2222-4222-8222-222222222551",
    brightDentalDiscovery: "22222222-2222-4222-8222-222222222561",
    apexLegalDiscovery: "22222222-2222-4222-8222-222222222571",
    harborOpsDiscovery: "22222222-2222-4222-8222-222222222581",
    harborOpsClosing: "22222222-2222-4222-8222-222222222582",
    metricFlowDiscovery: "22222222-2222-4222-8222-222222222591",
    signalHRDiscovery: "22222222-2222-4222-8222-222222222601",
    signalHRFollowUp: "22222222-2222-4222-8222-222222222602",
  },
  notes: {
    cloudLedgerDiscovery: "44444444-4444-4444-8444-444444444501",
    finStackDiscovery: "44444444-4444-4444-8444-444444444511",
    finStackFollowUp: "44444444-4444-4444-8444-444444444512",
    payRouteDiscovery: "44444444-4444-4444-8444-444444444521",
    payRouteClosing: "44444444-4444-4444-8444-444444444522",
    greenCartDiscovery: "44444444-4444-4444-8444-444444444531",
    loomWearDiscovery: "44444444-4444-4444-8444-444444444541",
    petNovaDiscovery: "44444444-4444-4444-8444-444444444551",
    brightDentalDiscovery: "44444444-4444-4444-8444-444444444561",
    apexLegalDiscovery: "44444444-4444-4444-8444-444444444571",
    harborOpsDiscovery: "44444444-4444-4444-8444-444444444581",
    harborOpsClosing: "44444444-4444-4444-8444-444444444582",
    metricFlowDiscovery: "44444444-4444-4444-8444-444444444591",
    signalHRDiscovery: "44444444-4444-4444-8444-444444444601",
    signalHRFollowUp: "44444444-4444-4444-8444-444444444602",
  },
  learning: "66666666-6666-4666-8666-666666666601",
} as const;

export const EXTRA_PROSPECT_IDS = Object.values(EXTRA_IDS.prospects);

export function buildExtraProspects(samId: string, rileyId: string) {
  return [
    {
      id: EXTRA_IDS.prospects.cloudLedger,
      company: "CloudLedger",
      website: "https://cloudledger.io",
      industry: "Fintech",
      employee_range: "85",
      gtm_maturity: "Series A — compliance-heavy content needs",
      buying_intent: "High — budget approved for Q2 content program",
      owner_id: samId,
      qualification_score: 71,
      stage: "demo_scheduled" as const,
      memory_json: {
        concerns: ["SOC2 content gaps", "Legal review on fintech claims"],
        buying_signals: ["Budget approved", "Demo scheduled"],
        stakeholders: ["Head of Marketing", "Compliance lead"],
        urgency: "high",
      },
    },
    {
      id: EXTRA_IDS.prospects.finStack,
      company: "FinStack",
      website: "https://finstack.com",
      industry: "B2B SaaS",
      employee_range: "200",
      gtm_maturity: "Series C — scaling enterprise pipeline",
      buying_intent: "Medium — stalled after pricing discussion",
      owner_id: samId,
      qualification_score: 64,
      stage: "follow_up" as const,
      memory_json: {
        concerns: ["Pricing pushback from CFO"],
        objections: ["Needs CFO on call", "ROI case not yet built"],
        stakeholders: ["VP Sales", "RevOps director"],
        next_actions: ["Send ROI deck", "Book CFO follow-up"],
        urgency: "medium",
      },
    },
    {
      id: EXTRA_IDS.prospects.payRoute,
      company: "PayRoute",
      website: "https://payroute.co",
      industry: "Payments",
      employee_range: "150",
      gtm_maturity: "Growth — expanding into EU markets",
      buying_intent: "High — pilot converted to annual",
      owner_id: samId,
      qualification_score: 82,
      stage: "won" as const,
      memory_json: {
        buying_signals: ["Signed annual after pilot", "EU launch content live"],
        stakeholders: ["CMO", "Localization lead"],
        sentiment: "positive",
      },
    },
    {
      id: EXTRA_IDS.prospects.greenCart,
      company: "GreenCart",
      website: "https://greencart.shop",
      industry: "D2C",
      employee_range: "60",
      gtm_maturity: "Early growth — testing organic channels",
      buying_intent: "Low-medium — slow decision process",
      owner_id: rileyId,
      qualification_score: 45,
      stage: "follow_up" as const,
      memory_json: {
        objections: ["Comparing two vendors", "Low urgency until Q4"],
        stakeholders: ["Founder", "Growth manager"],
        urgency: "low",
      },
    },
    {
      id: EXTRA_IDS.prospects.loomWear,
      company: "LoomWear",
      website: "https://loomwear.com",
      industry: "D2C",
      employee_range: "90",
      gtm_maturity: "Seasonal D2C — spring collection launch",
      buying_intent: "Medium-high — creative team bought in",
      owner_id: rileyId,
      qualification_score: 58,
      stage: "demo_scheduled" as const,
      memory_json: {
        buying_signals: ["Creative liked sample posts", "Launch in 6 weeks"],
        concerns: ["Seasonal timing", "Brand voice consistency"],
        stakeholders: ["Creative director", "Head of E-commerce"],
        urgency: "high",
      },
    },
    {
      id: EXTRA_IDS.prospects.petNova,
      company: "PetNova",
      website: "https://petnova.co",
      industry: "D2C",
      employee_range: "45",
      gtm_maturity: "Bootstrap — lean marketing team",
      buying_intent: "Low — budget frozen",
      owner_id: rileyId,
      qualification_score: 22,
      stage: "rejected" as const,
      memory_json: {
        objections: ["No budget this year", "Paused all agency spend"],
        sentiment: "negative",
        next_actions: ["Nurture for Q4 budget cycle"],
      },
    },
    {
      id: EXTRA_IDS.prospects.brightDental,
      company: "BrightDental Group",
      website: "https://brightdental.com",
      industry: "Healthcare",
      employee_range: "320",
      gtm_maturity: "Multi-location healthcare — local SEO focus",
      buying_intent: "Medium — evaluating content for patient acquisition",
      owner_id: rileyId,
      qualification_score: 67,
      stage: "discovery" as const,
      memory_json: {
        pain_points: ["Local SEO weak in new markets", "Compliance on medical content"],
        stakeholders: ["Marketing director", "Practice ops lead"],
        urgency: "medium",
      },
    },
    {
      id: EXTRA_IDS.prospects.apexLegal,
      company: "Apex Legal",
      website: "https://apexlegal.com",
      industry: "Professional services",
      employee_range: "110",
      gtm_maturity: "Regional law firm — thought leadership push",
      buying_intent: "Low — prefers in-house hire",
      owner_id: samId,
      qualification_score: 38,
      stage: "rejected" as const,
      memory_json: {
        objections: ["Wants in-house content hire", "Skeptical of outsourced legal content"],
        sentiment: "negative",
      },
    },
    {
      id: EXTRA_IDS.prospects.harborOps,
      company: "HarborOps",
      website: "https://harborops.io",
      industry: "Logistics SaaS",
      employee_range: "75",
      gtm_maturity: "Series A — first dedicated marketing hire",
      buying_intent: "High — legal review on MSA",
      owner_id: rileyId,
      qualification_score: 74,
      stage: "closing" as const,
      memory_json: {
        buying_signals: ["Legal review started", "Champion wants signature this month"],
        stakeholders: ["CEO", "Head of Marketing"],
        urgency: "high",
      },
    },
    {
      id: EXTRA_IDS.prospects.metricFlow,
      company: "MetricFlow",
      website: "https://metricflow.ai",
      industry: "B2B SaaS",
      employee_range: "55",
      gtm_maturity: "Seed — early GTM experiments",
      buying_intent: "Low — unclear pain on first call",
      owner_id: samId,
      qualification_score: 49,
      stage: "discovery" as const,
      memory_json: {
        concerns: ["Early stage — unclear pain", "Founder-led marketing"],
        urgency: "low",
      },
    },
    {
      id: EXTRA_IDS.prospects.signalHR,
      company: "SignalHR",
      website: "https://signalhr.com",
      industry: "HR Tech",
      employee_range: "130",
      gtm_maturity: "Series B — enterprise content motion",
      buying_intent: "Medium — security review gating deal",
      owner_id: rileyId,
      qualification_score: 61,
      stage: "follow_up" as const,
      memory_json: {
        objections: ["Needs security review", "Procurement involved"],
        buying_signals: ["Champion engaged", "Shared RFP timeline"],
        stakeholders: ["VP Marketing", "InfoSec"],
        urgency: "medium",
      },
    },
  ];
}

export function buildExtraManagerInsights() {
  return [
    { prospect_id: EXTRA_IDS.prospects.cloudLedger, health: "green", risk: "Security review in progress — on track", coaching: "Bring compliance lead into next demo.", pipeline_signal: "Demo scheduled — budget approved", patterns: ["Enterprise security", "Fintech compliance"] },
    { prospect_id: EXTRA_IDS.prospects.finStack, health: "yellow", risk: "CFO not engaged — pricing stall", coaching: "Stop sending collateral; book CFO with ROI model.", pipeline_signal: "Follow-up stalled on pricing", patterns: ["Pricing friction", "Missing economic buyer"] },
    { prospect_id: EXTRA_IDS.prospects.payRoute, health: "green", risk: "None — customer live", coaching: "Document EU launch win for fintech vertical.", pipeline_signal: "Converted — annual contract", patterns: ["Pilot conversion", "International expansion"] },
    { prospect_id: EXTRA_IDS.prospects.greenCart, health: "yellow", risk: "Low urgency until Q4", coaching: "Qualify hard timeline or deprioritize.", pipeline_signal: "Follow-up — slow D2C eval", patterns: ["Slow D2C", "Vendor comparison"] },
    { prospect_id: EXTRA_IDS.prospects.loomWear, health: "green", risk: "Seasonal deadline — must launch on time", coaching: "Anchor demo to spring collection dates.", pipeline_signal: "Demo scheduled — seasonal urgency", patterns: ["Creative buy-in", "Seasonal launch"] },
    { prospect_id: EXTRA_IDS.prospects.petNova, health: "red", risk: "Budget frozen — no path this year", coaching: "Move to nurture; don't invest prep time.", pipeline_signal: "Rejected — budget freeze", patterns: ["Budget freeze", "Bootstrap"] },
    { prospect_id: EXTRA_IDS.prospects.brightDental, health: "yellow", risk: "Healthcare compliance adds cycle time", coaching: "Lead with compliant content examples on first call.", pipeline_signal: "First call — local SEO pain", patterns: ["Healthcare compliance", "Multi-location"] },
    { prospect_id: EXTRA_IDS.prospects.apexLegal, health: "red", risk: "Build vs buy — prefers in-house hire", coaching: "Close lost; don't re-engage unless hiring fails.", pipeline_signal: "Rejected — in-house preference", patterns: ["Build vs buy", "Professional services"] },
    { prospect_id: EXTRA_IDS.prospects.harborOps, health: "green", risk: "Legal redlines — normal for closing stage", coaching: "Push for signature date before month end.", pipeline_signal: "Closing — legal review", patterns: ["Strong champion", "Closing motion"] },
    { prospect_id: EXTRA_IDS.prospects.metricFlow, health: "yellow", risk: "Unclear pain — may be too early", coaching: "Tight qualification on next call or disqualify.", pipeline_signal: "First call — early stage", patterns: ["Early stage", "Founder-led"] },
    { prospect_id: EXTRA_IDS.prospects.signalHR, health: "yellow", risk: "Security queue could slip quarter", coaching: "Offer to join infosec call; multi-thread to procurement.", pipeline_signal: "Follow-up — security review", patterns: ["Security gate", "Enterprise procurement"] },
  ];
}

export function buildPipelineMilestones() {
  return [
    { id: "77777777-7777-4777-8777-777777777201", prospect_id: EXTRA_IDS.prospects.cloudLedger, occurred_at: daysAgo(12), label: "Security review started", next_step: "Send SOC2 content pack", tone: "positive" },
    { id: "77777777-7777-4777-8777-777777777202", prospect_id: EXTRA_IDS.prospects.finStack, occurred_at: daysAgo(8), label: "Pricing objection raised", next_step: "ROI deck to CFO", tone: "warning" },
    { id: "77777777-7777-4777-8777-777777777203", prospect_id: EXTRA_IDS.prospects.payRoute, occurred_at: daysAgo(30), label: "Pilot signed → annual", next_step: "EU content kickoff", tone: "positive" },
    { id: "77777777-7777-4777-8777-777777777211", prospect_id: EXTRA_IDS.prospects.greenCart, occurred_at: daysAgo(15), label: "Weak urgency signal", next_step: "Qualify Q4 timeline", tone: "warning" },
    { id: "77777777-7777-4777-8777-777777777212", prospect_id: EXTRA_IDS.prospects.loomWear, occurred_at: daysAgo(5), label: "Creative approved samples", next_step: "Demo editorial workflow", tone: "positive" },
    { id: "77777777-7777-4777-8777-777777777213", prospect_id: EXTRA_IDS.prospects.petNova, occurred_at: daysAgo(20), label: "Budget freeze confirmed", next_step: "Nurture Q4", tone: "negative" },
    { id: "77777777-7777-4777-8777-777777777214", prospect_id: EXTRA_IDS.prospects.brightDental, occurred_at: daysAgo(7), label: "Local SEO gaps identified", next_step: "Discovery follow-up", tone: "neutral" },
    { id: "77777777-7777-4777-8777-777777777221", prospect_id: EXTRA_IDS.prospects.apexLegal, occurred_at: daysAgo(11), label: "In-house hire preferred", next_step: "Close lost", tone: "negative" },
    { id: "77777777-7777-4777-8777-777777777222", prospect_id: EXTRA_IDS.prospects.harborOps, occurred_at: daysAgo(3), label: "Legal redlines sent", next_step: "Close by month end", tone: "positive" },
    { id: "77777777-7777-4777-8777-777777777223", prospect_id: EXTRA_IDS.prospects.metricFlow, occurred_at: daysAgo(6), label: "First call — pain unclear", next_step: "Qualify or disqualify", tone: "warning" },
    { id: "77777777-7777-4777-8777-777777777224", prospect_id: EXTRA_IDS.prospects.signalHR, occurred_at: daysAgo(6), label: "Security questionnaire sent", next_step: "Schedule security call", tone: "neutral" },
  ];
}

const MEET_LINK = "https://meet.google.com/gushwork-demo";

export function buildExtraMeetings(samId: string, rileyId: string) {
  return [
    {
      id: EXTRA_IDS.meetings.cloudLedgerDiscovery,
      prospect_id: EXTRA_IDS.prospects.cloudLedger,
      rep_id: samId,
      type: "discovery" as const,
      scheduled_at: daysAgo(18),
      completed_at: daysAgo(18),
      triage_status: "proceed" as const,
      triage_explanation: "Budget approved — strong fintech fit.",
      meeting_link: MEET_LINK,
      open_points: ["Send SOC2 content examples"],
    },
    {
      id: EXTRA_IDS.meetings.cloudLedgerDemo,
      prospect_id: EXTRA_IDS.prospects.cloudLedger,
      rep_id: samId,
      type: "demo" as const,
      scheduled_at: daysFromNow(2),
      triage_status: "proceed" as const,
      triage_explanation: "Compliance lead joining — high intent.",
      meeting_link: MEET_LINK,
      open_points: [],
    },
    {
      id: EXTRA_IDS.meetings.finStackDiscovery,
      prospect_id: EXTRA_IDS.prospects.finStack,
      rep_id: samId,
      type: "discovery" as const,
      scheduled_at: daysAgo(22),
      completed_at: daysAgo(22),
      triage_status: "proceed" as const,
      triage_explanation: "Enterprise SaaS with clear content gap.",
      meeting_link: MEET_LINK,
      open_points: [],
    },
    {
      id: EXTRA_IDS.meetings.finStackFollowUp,
      prospect_id: EXTRA_IDS.prospects.finStack,
      rep_id: samId,
      type: "demo" as const,
      scheduled_at: daysAgo(8),
      completed_at: daysAgo(8),
      triage_status: "warning" as const,
      triage_explanation: "CFO not on call — pricing stall risk.",
      meeting_link: MEET_LINK,
      open_points: ["Book CFO with ROI deck"],
    },
    {
      id: EXTRA_IDS.meetings.payRouteDiscovery,
      prospect_id: EXTRA_IDS.prospects.payRoute,
      rep_id: samId,
      type: "discovery" as const,
      scheduled_at: daysAgo(45),
      completed_at: daysAgo(45),
      triage_status: "proceed" as const,
      triage_explanation: "EU expansion content need — pilot candidate.",
      meeting_link: MEET_LINK,
      open_points: [],
    },
    {
      id: EXTRA_IDS.meetings.payRouteClosing,
      prospect_id: EXTRA_IDS.prospects.payRoute,
      rep_id: samId,
      type: "closing" as const,
      scheduled_at: daysAgo(30),
      completed_at: daysAgo(30),
      triage_status: "proceed" as const,
      triage_explanation: "Pilot converted — annual signed.",
      meeting_link: MEET_LINK,
      open_points: ["EU content kickoff"],
    },
    {
      id: EXTRA_IDS.meetings.greenCartDiscovery,
      prospect_id: EXTRA_IDS.prospects.greenCart,
      rep_id: rileyId,
      type: "discovery" as const,
      scheduled_at: daysAgo(15),
      completed_at: daysAgo(15),
      triage_status: "warning" as const,
      triage_explanation: "Low urgency D2C — qualify timeline hard.",
      meeting_link: MEET_LINK,
      open_points: ["Confirm Q4 decision date"],
    },
    {
      id: EXTRA_IDS.meetings.loomWearDiscovery,
      prospect_id: EXTRA_IDS.prospects.loomWear,
      rep_id: rileyId,
      type: "discovery" as const,
      scheduled_at: daysAgo(12),
      completed_at: daysAgo(12),
      triage_status: "proceed" as const,
      triage_explanation: "Seasonal launch deadline — creative bought in.",
      meeting_link: MEET_LINK,
      open_points: [],
    },
    {
      id: EXTRA_IDS.meetings.loomWearDemo,
      prospect_id: EXTRA_IDS.prospects.loomWear,
      rep_id: rileyId,
      type: "demo" as const,
      scheduled_at: daysFromNow(3),
      triage_status: "proceed" as const,
      triage_explanation: "Demo scheduled — anchor to collection launch.",
      meeting_link: MEET_LINK,
      open_points: [],
    },
    {
      id: EXTRA_IDS.meetings.petNovaDiscovery,
      prospect_id: EXTRA_IDS.prospects.petNova,
      rep_id: rileyId,
      type: "discovery" as const,
      scheduled_at: daysAgo(20),
      completed_at: daysAgo(20),
      triage_status: "reject" as const,
      triage_explanation: "Budget frozen — no path this year.",
      meeting_link: MEET_LINK,
      open_points: ["Nurture for Q4"],
    },
    {
      id: EXTRA_IDS.meetings.brightDentalDiscovery,
      prospect_id: EXTRA_IDS.prospects.brightDental,
      rep_id: rileyId,
      type: "discovery" as const,
      scheduled_at: daysAgo(7),
      completed_at: daysAgo(7),
      triage_status: "proceed" as const,
      triage_explanation: "Multi-location healthcare — local SEO pain validated.",
      meeting_link: MEET_LINK,
      open_points: ["Send compliant content samples"],
    },
    {
      id: EXTRA_IDS.meetings.apexLegalDiscovery,
      prospect_id: EXTRA_IDS.prospects.apexLegal,
      rep_id: samId,
      type: "discovery" as const,
      scheduled_at: daysAgo(11),
      completed_at: daysAgo(11),
      triage_status: "reject" as const,
      triage_explanation: "Prefers in-house hire — low fit.",
      meeting_link: MEET_LINK,
      open_points: ["Close lost"],
    },
    {
      id: EXTRA_IDS.meetings.harborOpsDiscovery,
      prospect_id: EXTRA_IDS.prospects.harborOps,
      rep_id: rileyId,
      type: "discovery" as const,
      scheduled_at: daysAgo(18),
      completed_at: daysAgo(18),
      triage_status: "proceed" as const,
      triage_explanation: "Logistics SaaS — first marketing hire, strong champion.",
      meeting_link: MEET_LINK,
      open_points: [],
    },
    {
      id: EXTRA_IDS.meetings.harborOpsClosing,
      prospect_id: EXTRA_IDS.prospects.harborOps,
      rep_id: rileyId,
      type: "closing" as const,
      scheduled_at: daysAgo(3),
      completed_at: daysAgo(3),
      triage_status: "proceed" as const,
      triage_explanation: "Legal redlines — closing this month.",
      meeting_link: MEET_LINK,
      open_points: ["Signature by month end"],
    },
    {
      id: EXTRA_IDS.meetings.metricFlowDiscovery,
      prospect_id: EXTRA_IDS.prospects.metricFlow,
      rep_id: samId,
      type: "discovery" as const,
      scheduled_at: daysAgo(6),
      completed_at: daysAgo(6),
      triage_status: "warning" as const,
      triage_explanation: "Early stage — pain not yet clear.",
      meeting_link: MEET_LINK,
      open_points: ["Qualify on follow-up or disqualify"],
    },
    {
      id: EXTRA_IDS.meetings.signalHRDiscovery,
      prospect_id: EXTRA_IDS.prospects.signalHR,
      rep_id: rileyId,
      type: "discovery" as const,
      scheduled_at: daysAgo(20),
      completed_at: daysAgo(20),
      triage_status: "proceed" as const,
      triage_explanation: "Enterprise HR tech — security gate expected.",
      meeting_link: MEET_LINK,
      open_points: [],
    },
    {
      id: EXTRA_IDS.meetings.signalHRFollowUp,
      prospect_id: EXTRA_IDS.prospects.signalHR,
      rep_id: rileyId,
      type: "demo" as const,
      scheduled_at: daysAgo(6),
      completed_at: daysAgo(6),
      triage_status: "warning" as const,
      triage_explanation: "Security questionnaire sent — procurement involved.",
      meeting_link: MEET_LINK,
      open_points: ["Schedule security call"],
    },
  ];
}

export function buildExtraNotes() {
  return [
    {
      id: EXTRA_IDS.notes.cloudLedgerDiscovery,
      meeting_id: EXTRA_IDS.meetings.cloudLedgerDiscovery,
      raw_notes:
        "Head of marketing confirmed Q2 budget. Compliance lead needs SOC2-aligned content examples before demo.",
      structured_summary: {
        pain_points: ["SOC2 content gaps", "Compliance review on fintech claims"],
        stakeholders: ["Head of Marketing", "Compliance lead"],
        sentiment: "positive",
        objections: [],
        next_actions: ["Send SOC2 content pack", "Book demo with compliance"],
        pipeline_stage: "demo_scheduled",
      },
    },
    {
      id: EXTRA_IDS.notes.finStackDiscovery,
      meeting_id: EXTRA_IDS.meetings.finStackDiscovery,
      raw_notes:
        "VP Sales engaged. RevOps wants faster content for enterprise pipeline. Good discovery — follow up with workflow demo.",
      structured_summary: {
        pain_points: ["Enterprise content backlog"],
        stakeholders: ["VP Sales", "RevOps director"],
        sentiment: "positive",
        objections: [],
        next_actions: ["Book workflow demo"],
        pipeline_stage: "follow_up",
      },
    },
    {
      id: EXTRA_IDS.notes.finStackFollowUp,
      meeting_id: EXTRA_IDS.meetings.finStackFollowUp,
      raw_notes:
        "Demo went well but pricing came up early. CFO was not on the call — need ROI case before next step.",
      structured_summary: {
        pain_points: ["Pricing pushback"],
        stakeholders: ["VP Sales"],
        sentiment: "cautious",
        objections: ["Needs CFO on call", "ROI case not built"],
        next_actions: ["Send ROI deck", "Book CFO follow-up"],
        pipeline_stage: "follow_up",
      },
    },
    {
      id: EXTRA_IDS.notes.payRouteDiscovery,
      meeting_id: EXTRA_IDS.meetings.payRouteDiscovery,
      raw_notes:
        "EU expansion driving content need. CMO wants pilot on two markets before annual commitment.",
      structured_summary: {
        pain_points: ["EU localization content gap"],
        stakeholders: ["CMO", "Localization lead"],
        sentiment: "positive",
        objections: [],
        next_actions: ["Propose 30-day pilot"],
        pipeline_stage: "follow_up",
      },
    },
    {
      id: EXTRA_IDS.notes.payRouteClosing,
      meeting_id: EXTRA_IDS.meetings.payRouteClosing,
      raw_notes:
        "Pilot exceeded targets. Signed annual — EU content kickoff next week.",
      structured_summary: {
        pain_points: [],
        stakeholders: ["CMO"],
        sentiment: "positive",
        objections: [],
        next_actions: ["EU content kickoff"],
        pipeline_stage: "won",
      },
    },
    {
      id: EXTRA_IDS.notes.greenCartDiscovery,
      meeting_id: EXTRA_IDS.meetings.greenCartDiscovery,
      raw_notes:
        "Founder comparing two vendors. No urgency until Q4 — weak timeline.",
      structured_summary: {
        pain_points: ["Organic growth plateau"],
        stakeholders: ["Founder", "Growth manager"],
        sentiment: "neutral",
        objections: ["Comparing vendors", "Low urgency"],
        next_actions: ["Qualify Q4 timeline"],
        pipeline_stage: "follow_up",
      },
    },
    {
      id: EXTRA_IDS.notes.loomWearDiscovery,
      meeting_id: EXTRA_IDS.meetings.loomWearDiscovery,
      raw_notes:
        "Creative director loved sample posts. Spring collection launch in 6 weeks — demo scheduled.",
      structured_summary: {
        pain_points: ["Seasonal content deadline"],
        stakeholders: ["Creative director", "Head of E-commerce"],
        sentiment: "positive",
        objections: [],
        next_actions: ["Demo editorial workflow"],
        pipeline_stage: "demo_scheduled",
      },
    },
    {
      id: EXTRA_IDS.notes.petNovaDiscovery,
      meeting_id: EXTRA_IDS.meetings.petNovaDiscovery,
      raw_notes:
        "All agency spend frozen this year. Friendly but no budget — mark rejected and nurture.",
      structured_summary: {
        pain_points: [],
        stakeholders: ["Founder"],
        sentiment: "negative",
        objections: ["Budget frozen"],
        next_actions: ["Nurture for Q4 budget cycle"],
        pipeline_stage: "rejected",
      },
    },
    {
      id: EXTRA_IDS.notes.brightDentalDiscovery,
      meeting_id: EXTRA_IDS.meetings.brightDentalDiscovery,
      raw_notes:
        "Marketing director flagged weak local SEO in new markets. Compliance on medical claims is a concern.",
      structured_summary: {
        pain_points: ["Local SEO in new markets", "Medical content compliance"],
        stakeholders: ["Marketing director", "Practice ops lead"],
        sentiment: "positive",
        objections: [],
        next_actions: ["Send compliant content samples", "Book follow-up"],
        pipeline_stage: "discovery",
      },
    },
    {
      id: EXTRA_IDS.notes.apexLegalDiscovery,
      meeting_id: EXTRA_IDS.meetings.apexLegalDiscovery,
      raw_notes:
        "Managing partner prefers hiring in-house writer. Skeptical of outsourced legal thought leadership.",
      structured_summary: {
        pain_points: [],
        stakeholders: ["Managing partner"],
        sentiment: "negative",
        objections: ["In-house hire preferred"],
        next_actions: ["Close lost"],
        pipeline_stage: "rejected",
      },
    },
    {
      id: EXTRA_IDS.notes.harborOpsDiscovery,
      meeting_id: EXTRA_IDS.meetings.harborOpsDiscovery,
      raw_notes:
        "CEO and first marketing hire on call. Strong champion — wants to move fast after Series A.",
      structured_summary: {
        pain_points: ["No dedicated content owner"],
        stakeholders: ["CEO", "Head of Marketing"],
        sentiment: "positive",
        objections: [],
        next_actions: ["Send proposal", "Book closing call"],
        pipeline_stage: "closing",
      },
    },
    {
      id: EXTRA_IDS.notes.harborOpsClosing,
      meeting_id: EXTRA_IDS.meetings.harborOpsClosing,
      raw_notes:
        "Legal sent redlines. Champion wants signature before month end.",
      structured_summary: {
        pain_points: [],
        stakeholders: ["CEO", "Head of Marketing"],
        sentiment: "positive",
        objections: [],
        next_actions: ["Close by month end"],
        pipeline_stage: "closing",
      },
    },
    {
      id: EXTRA_IDS.notes.metricFlowDiscovery,
      meeting_id: EXTRA_IDS.meetings.metricFlowDiscovery,
      raw_notes:
        "Founder-led GTM — pain unclear on first call. May be too early.",
      structured_summary: {
        pain_points: [],
        stakeholders: ["Founder"],
        sentiment: "neutral",
        objections: [],
        next_actions: ["Qualify on follow-up or disqualify"],
        pipeline_stage: "discovery",
      },
    },
    {
      id: EXTRA_IDS.notes.signalHRDiscovery,
      meeting_id: EXTRA_IDS.meetings.signalHRDiscovery,
      raw_notes:
        "VP Marketing engaged. Enterprise motion — expect security and procurement gates.",
      structured_summary: {
        pain_points: ["Enterprise content scale"],
        stakeholders: ["VP Marketing"],
        sentiment: "positive",
        objections: [],
        next_actions: ["Send security questionnaire"],
        pipeline_stage: "follow_up",
      },
    },
    {
      id: EXTRA_IDS.notes.signalHRFollowUp,
      meeting_id: EXTRA_IDS.meetings.signalHRFollowUp,
      raw_notes:
        "Security questionnaire sent. InfoSec review in queue — schedule joint call with procurement.",
      structured_summary: {
        pain_points: ["Security review queue"],
        stakeholders: ["VP Marketing", "InfoSec"],
        sentiment: "cautious",
        objections: ["Security review required"],
        next_actions: ["Schedule security call"],
        pipeline_stage: "follow_up",
      },
    },
  ];
}

export function buildLearningLeaps() {
  return {
    id: EXTRA_IDS.learning,
    worked_well: [
      "Leading with customer proof in SaaS demos",
      "Asking for economic buyer early on follow-ups",
      "Pilot offers unblock quality objections",
      "Industry-specific case studies increase reply rates",
    ],
    didnt_work: [
      "Deep pricing talk before value established",
      "Generic discovery questions on competitive deals",
      "Sending collateral without a meeting commitment",
      "Technical deep-dives when champion isn't technical",
    ],
  };
}

export function buildRepDevelopmentAreas() {
  return [
    {
      email: "rep@gushwork.demo",
      development_areas: [
        "Strong discovery — tighten executive storytelling",
        "Good objection handling on quality concerns",
      ],
    },
    {
      email: EXTRA_REP_EMAILS.sam,
      development_areas: [
        "Insufficient technical knowledge about product",
        "Pitch structure jumps to pricing too early",
        "Needs stronger multi-threading on enterprise deals",
      ],
    },
    {
      email: EXTRA_REP_EMAILS.riley,
      development_areas: [
        "Unable to negotiate on pricing confidently",
        "Discovery questions too generic for D2C",
        "Weak close — rarely asks for commitment",
      ],
    },
  ];
}
