import { SEED_IDS, daysAgo, daysFromNow } from "./ids";

const MEET_LINK = "https://meet.google.com/gushwork-demo";

export function buildProspects(repId: string) {
  return [
    {
      id: SEED_IDS.prospects.metricPulse,
      company: "MetricPulse",
      website: "https://metricpulse.io",
      industry: "B2B SaaS",
      employee_range: "95",
      gtm_maturity: "Series A — building inbound engine",
      buying_intent: "Medium — exploring first SEO partner",
      owner_id: repId,
      qualification_score: 58,
      stage: "discovery" as const,
      memory_json: {
        pain_points: ["Inbound flat for two quarters", "No dedicated SEO owner"],
        stakeholders: ["VP Marketing", "Head of Content (not met yet)"],
        timeline: "Evaluating partners this month — follow-up overdue",
        next_actions: ["Send SaaS discovery case study", "Book follow-up with head of content"],
        sentiment: "neutral",
        urgency: "medium",
      },
    },
    {
      id: SEED_IDS.prospects.nomadCommerce,
      company: "Nomad Commerce",
      website: "https://nomadcommerce.com",
      industry: "D2C",
      employee_range: "300",
      gtm_maturity: "Growth stage — multi-channel D2C",
      buying_intent: "Medium — evaluating consolidated SEO partner",
      owner_id: repId,
      qualification_score: 52,
      stage: "follow_up" as const,
      memory_json: {
        concerns: ["Traffic plateau", "Multiple agency relationships"],
        buying_signals: ["Attended full demo", "Asked about migration path"],
        pain_points: ["Organic traffic flat", "Agency coordination overhead"],
        stakeholders: ["CMO", "Growth lead"],
        timeline: "Decision by end of quarter",
        objections: ["Shopping three vendors", "CMO not yet on call"],
        next_actions: ["Get CMO on closing call", "Send differentiation one-pager"],
        sentiment: "cautious",
        urgency: "medium",
      },
    },
    {
      id: SEED_IDS.prospects.stackline,
      company: "Stackline",
      website: "https://stackline.com",
      industry: "B2B SaaS",
      employee_range: "180",
      gtm_maturity: "Series B — expanding into new verticals",
      buying_intent: "Medium-high — needs content for two new ICPs",
      owner_id: repId,
      qualification_score: 63,
      stage: "follow_up" as const,
      memory_json: {
        concerns: ["Security review queue", "Internal bandwidth for briefs"],
        buying_signals: ["Champion re-engaged after QBR", "Shared content calendar", "Infosec approved questionnaire"],
        pain_points: ["Vertical launch content backlog", "Slow agency turnaround"],
        stakeholders: ["Director of Demand Gen", "Content lead"],
        timeline: "Post-security demo needed before Q3 vertical launch",
        objections: [],
        next_actions: ["Schedule post-security demo", "Align on Q3 vertical launch dates"],
        sentiment: "positive",
        urgency: "high",
      },
    },
    {
      id: SEED_IDS.prospects.velocityHr,
      company: "VelocityHR",
      website: "https://velocityhr.io",
      industry: "B2B SaaS",
      employee_range: "120",
      gtm_maturity: "Series B — scaling content-led growth",
      buying_intent: "High — active SEO expansion initiative",
      owner_id: repId,
      qualification_score: 78,
      stage: "demo_scheduled" as const,
      memory_json: {
        concerns: ["Content quality at scale", "Hitting 25 blogs/month target"],
        buying_signals: ["Urgency high", "Second demo scheduled", "VP Marketing engaged"],
        pain_points: ["Content team overloaded", "SEO scaling bottleneck"],
        stakeholders: ["Head of Content", "VP Marketing"],
        timeline: "Q2 launch window",
        objections: ["Concern around AI-assisted content quality"],
        next_actions: ["Address quality workflow in next demo", "Secure pilot scope"],
        sentiment: "positive",
        urgency: "high",
      },
    },
    {
      id: SEED_IDS.prospects.relayCommerce,
      company: "Relay Commerce",
      website: "https://relaycommerce.co",
      industry: "D2C",
      employee_range: "140",
      gtm_maturity: "Profitable D2C — scaling organic channel",
      buying_intent: "High — signed after pilot",
      owner_id: repId,
      qualification_score: 86,
      stage: "won" as const,
      memory_json: {
        buying_signals: ["Signed annual contract", "Pilot exceeded traffic target"],
        pain_points: ["Paid CAC rising", "Needed faster blog velocity"],
        stakeholders: ["CMO", "Head of Growth"],
        timeline: "Kickoff completed",
        next_actions: ["Onboarding handoff to CS", "Quarterly business review in 90 days"],
        sentiment: "positive",
        urgency: "high",
      },
    },
    {
      id: SEED_IDS.prospects.searchForge,
      company: "SearchForge Digital",
      website: "https://searchforgedigital.com",
      industry: "Agency",
      employee_range: "40",
      gtm_maturity: "Established agency — services shop",
      buying_intent: "Low — likely research / competitive intel",
      owner_id: repId,
      qualification_score: 18,
      stage: "rejected" as const,
      memory_json: {
        concerns: ["Deep implementation questions", "Possible competitor research"],
        buying_signals: [],
        pain_points: ["No validated buyer pain — benchmarking tone"],
        stakeholders: ["Founder (solo on call)"],
        objections: ["Asked for internal build specs and tooling stack"],
        next_actions: ["Do not pursue — mark as reject"],
        sentiment: "negative",
        urgency: "low",
      },
    },
  ];
}

export function buildMeetings(repId: string) {
  return [
    // First call — MetricPulse (completed discovery, no follow-up scheduled yet)
    {
      id: SEED_IDS.meetings.metricPulseDiscovery,
      prospect_id: SEED_IDS.prospects.metricPulse,
      rep_id: repId,
      type: "discovery" as const,
      scheduled_at: daysAgo(7),
      completed_at: daysAgo(7),
      triage_status: "proceed" as const,
      triage_explanation: "Clear pain on inbound — worth a structured follow-up.",
      meeting_link: MEET_LINK,
      open_points: ["Send SaaS discovery case study", "Book follow-up with head of content"],
    },
    // Follow up — Nomad (two completed + one upcoming)
    {
      id: SEED_IDS.meetings.nomadDiscovery,
      prospect_id: SEED_IDS.prospects.nomadCommerce,
      rep_id: repId,
      type: "discovery" as const,
      scheduled_at: daysAgo(28),
      completed_at: daysAgo(28),
      triage_status: "warning" as const,
      triage_explanation: "Multiple agencies in mix — qualify consolidation appetite early.",
      meeting_link: MEET_LINK,
      open_points: [],
    },
    {
      id: SEED_IDS.meetings.nomadDemo,
      prospect_id: SEED_IDS.prospects.nomadCommerce,
      rep_id: repId,
      type: "demo" as const,
      scheduled_at: daysAgo(14),
      completed_at: daysAgo(14),
      triage_status: "warning" as const,
      triage_explanation: "Demo completed but competitive eval detected — stall risk.",
      meeting_link: MEET_LINK,
      open_points: [],
    },
    {
      id: SEED_IDS.meetings.nomadClosing,
      prospect_id: SEED_IDS.prospects.nomadCommerce,
      rep_id: repId,
      type: "closing" as const,
      scheduled_at: daysFromNow(6),
      completed_at: null,
      triage_status: "warning" as const,
      triage_explanation: "Proceed with caution — need economic buyer and decision date.",
      meeting_link: MEET_LINK,
      open_points: [
        "Get CMO on the call",
        "Confirm decision timeline",
        "Differentiate vs incumbent agencies",
      ],
    },
    // Follow up — Stackline (discovery → demo → security cleared, needs next demo)
    {
      id: SEED_IDS.meetings.stacklineDiscovery,
      prospect_id: SEED_IDS.prospects.stackline,
      rep_id: repId,
      type: "discovery" as const,
      scheduled_at: daysAgo(38),
      completed_at: daysAgo(38),
      triage_status: "proceed" as const,
      triage_explanation: "Vertical launch pain is concrete — good fit for Gushwork.",
      meeting_link: MEET_LINK,
      open_points: [],
    },
    {
      id: SEED_IDS.meetings.stacklineFollowUp1,
      prospect_id: SEED_IDS.prospects.stackline,
      rep_id: repId,
      type: "demo" as const,
      scheduled_at: daysAgo(22),
      completed_at: daysAgo(22),
      triage_status: "proceed" as const,
      triage_explanation: "Champion engaged — security review is the main gate.",
      meeting_link: MEET_LINK,
      open_points: [],
    },
    {
      id: SEED_IDS.meetings.stacklineFollowUp2,
      prospect_id: SEED_IDS.prospects.stackline,
      rep_id: repId,
      type: "demo" as const,
      scheduled_at: daysAgo(8),
      completed_at: daysAgo(8),
      triage_status: "proceed" as const,
      triage_explanation: "Security cleared — schedule post-infosec demo with content lead.",
      meeting_link: MEET_LINK,
      open_points: [
        "Schedule post-security demo",
        "Confirm Q3 vertical launch dates",
      ],
    },
    // Demo scheduled — VelocityHR (past meetings + upcoming demo)
    {
      id: SEED_IDS.meetings.velocityDiscovery,
      prospect_id: SEED_IDS.prospects.velocityHr,
      rep_id: repId,
      type: "discovery" as const,
      scheduled_at: daysAgo(24),
      completed_at: daysAgo(24),
      triage_status: "proceed" as const,
      triage_explanation: "Strong fit: B2B SaaS with clear content volume gap and timeline.",
      meeting_link: MEET_LINK,
      open_points: [],
    },
    {
      id: SEED_IDS.meetings.velocityDemo,
      prospect_id: SEED_IDS.prospects.velocityHr,
      rep_id: repId,
      type: "demo" as const,
      scheduled_at: daysAgo(11),
      completed_at: daysAgo(11),
      triage_status: "proceed" as const,
      triage_explanation: "Discovery validated pain; demo appropriate.",
      meeting_link: MEET_LINK,
      open_points: [],
    },
    {
      id: SEED_IDS.meetings.velocityFollowUpDemo,
      prospect_id: SEED_IDS.prospects.velocityHr,
      rep_id: repId,
      type: "demo" as const,
      scheduled_at: daysFromNow(2),
      completed_at: null,
      triage_status: "proceed" as const,
      triage_explanation: "Follow-up demo to address quality concerns — high intent signal.",
      meeting_link: MEET_LINK,
      open_points: [
        "Address AI content quality concerns",
        "Confirm editorial review workflow",
        "Secure pilot scope",
      ],
    },
    // Converted — Relay Commerce (completed closing only in past column)
    {
      id: SEED_IDS.meetings.relayDiscovery,
      prospect_id: SEED_IDS.prospects.relayCommerce,
      rep_id: repId,
      type: "discovery" as const,
      scheduled_at: daysAgo(52),
      completed_at: daysAgo(52),
      triage_status: "proceed" as const,
      triage_explanation: "Strong D2C fit with rising CAC pressure.",
      meeting_link: MEET_LINK,
      open_points: [],
    },
    {
      id: SEED_IDS.meetings.relayDemo,
      prospect_id: SEED_IDS.prospects.relayCommerce,
      rep_id: repId,
      type: "demo" as const,
      scheduled_at: daysAgo(35),
      completed_at: daysAgo(35),
      triage_status: "proceed" as const,
      triage_explanation: "Demo landed — pilot scope agreed in principle.",
      meeting_link: MEET_LINK,
      open_points: [],
    },
    {
      id: SEED_IDS.meetings.relayClosing,
      prospect_id: SEED_IDS.prospects.relayCommerce,
      rep_id: repId,
      type: "closing" as const,
      scheduled_at: daysAgo(9),
      completed_at: daysAgo(9),
      triage_status: "proceed" as const,
      triage_explanation: "Deal closed — annual contract signed after successful pilot.",
      meeting_link: MEET_LINK,
      open_points: ["Onboarding handoff to CS"],
    },
    // Rejected — SearchForge (one completed discovery)
    {
      id: SEED_IDS.meetings.searchForgeDiscovery,
      prospect_id: SEED_IDS.prospects.searchForge,
      rep_id: repId,
      type: "discovery" as const,
      scheduled_at: daysAgo(18),
      completed_at: daysAgo(18),
      triage_status: "reject" as const,
      triage_explanation: "Agency asking implementation internals — likely competitor research.",
      meeting_link: MEET_LINK,
      open_points: [],
    },
  ];
}

export function buildBriefs() {
  return [
    {
      id: SEED_IDS.briefs.velocityFollowUpDemo,
      meeting_id: SEED_IDS.meetings.velocityFollowUpDemo,
      source: "ai" as const,
      brief: {
        prospect_summary:
          "VelocityHR (120 emp, B2B SaaS) scales SEO content 8→25 blogs/mo. Content team overloaded.",
        previous_concerns: ["AI content quality at scale", "Editorial review bandwidth"],
        buying_signals: ["High urgency — Q2 window", "Returned for second demo", "VP Marketing engaged"],
        deal_risks: ["Quality objection unresolved from last demo"],
        questions_to_ask: [
          "What does your editorial review process look like today?",
          "Who signs off if quality bar is met?",
          "What happens if you miss the Q2 content target?",
        ],
        recommended_outcome: "Confirm quality workflow + secure pilot scope for 30 days.",
      },
    },
    {
      id: SEED_IDS.briefs.nomadClosing,
      meeting_id: SEED_IDS.meetings.nomadClosing,
      source: "ai" as const,
      brief: {
        prospect_summary:
          "Nomad Commerce (300 emp, D2C) — traffic plateau, consolidating three SEO vendors.",
        previous_concerns: ["Shopping three vendors", "CMO not yet engaged"],
        buying_signals: ["Attended full demo", "Asked about migration path"],
        deal_risks: ["No decision date", "Incumbent agency relationships"],
        questions_to_ask: [
          "What would need to be true to consolidate on one partner?",
          "Can we get the CMO on this call?",
          "What is the decision timeline?",
        ],
        recommended_outcome: "Secure economic buyer meeting and explicit decision date.",
      },
    },
  ];
}

export function buildNotes() {
  return [
    {
      id: SEED_IDS.notes.metricPulseDiscovery,
      meeting_id: SEED_IDS.meetings.metricPulseDiscovery,
      raw_notes:
        "First discovery call. Inbound flat two quarters. VP Marketing owns budget but no SEO hire planned. Pain is real — they want a partner recommendation by month end. Follow up with head of content.",
      structured_summary: {
        pain_points: ["Inbound flat for two quarters", "No dedicated SEO owner"],
        stakeholders: ["VP Marketing"],
        timeline: "Evaluating partners this month",
        sentiment: "neutral",
        objections: [],
        next_actions: ["Send SaaS discovery case study", "Book follow-up with head of content"],
        pipeline_stage: "discovery",
      },
    },
    {
      id: SEED_IDS.notes.nomadDiscovery,
      meeting_id: SEED_IDS.meetings.nomadDiscovery,
      raw_notes:
        "Traffic plateau for 6 months. Already using two SEO agencies plus in-house contractor. CMO open to consolidating if we can show D2C-specific wins.",
      structured_summary: {
        pain_points: ["Traffic plateau", "Agency sprawl"],
        budget: "Combined ~$18k/mo across vendors",
        stakeholders: ["CMO", "Growth lead"],
        timeline: "Evaluating through end of quarter",
        sentiment: "neutral",
        objections: ["Incumbent agency relationships"],
        next_actions: ["Book demo", "Send D2C case studies"],
        pipeline_stage: "follow_up",
      },
    },
    {
      id: SEED_IDS.notes.nomadDemo,
      meeting_id: SEED_IDS.meetings.nomadDemo,
      raw_notes:
        "Demo completed. Liked reporting. Evaluating us plus two alternatives. Growth lead engaged, CMO absent. Schedule follow-up to get CMO on call.",
      structured_summary: {
        pain_points: ["Traffic plateau", "Vendor comparison fatigue"],
        stakeholders: ["Growth lead", "CMO (not on call)"],
        timeline: "Unknown — multi-vendor eval",
        sentiment: "cautious",
        objections: ["Shopping behavior", "CMO not engaged yet"],
        next_actions: ["Send differentiation one-pager", "Push for CMO on next call"],
        pipeline_stage: "follow_up",
      },
    },
    {
      id: SEED_IDS.notes.stacklineDiscovery,
      meeting_id: SEED_IDS.meetings.stacklineDiscovery,
      raw_notes:
        "Launching content for two new verticals. Current agency turnaround is too slow. Demand gen director is champion. Follow up after they share calendar.",
      structured_summary: {
        pain_points: ["Vertical launch backlog", "Slow agency turnaround"],
        stakeholders: ["Director of Demand Gen"],
        sentiment: "positive",
        objections: [],
        next_actions: ["Share vertical launch case study", "Book workflow demo"],
        pipeline_stage: "follow_up",
      },
    },
    {
      id: SEED_IDS.notes.stacklineFollowUp1,
      meeting_id: SEED_IDS.meetings.stacklineFollowUp1,
      raw_notes:
        "Workflow demo went well. Security review is the blocker — questionnaire sent. Reconnect in two weeks after infosec review.",
      structured_summary: {
        pain_points: ["Security review queue"],
        stakeholders: ["Director of Demand Gen", "Content lead"],
        sentiment: "positive",
        objections: ["Needs security sign-off"],
        next_actions: ["Complete security questionnaire", "Schedule follow-up in two weeks"],
        pipeline_stage: "follow_up",
      },
    },
    {
      id: SEED_IDS.notes.stacklineFollowUp2,
      meeting_id: SEED_IDS.meetings.stacklineFollowUp2,
      raw_notes:
        "Infosec approved the questionnaire. Champion wants a technical demo with the content lead before Q3 vertical launch. No follow-up on the calendar yet — schedule the post-security demo.",
      structured_summary: {
        pain_points: ["Vertical launch dates approaching"],
        stakeholders: ["Director of Demand Gen", "Content lead"],
        sentiment: "positive",
        objections: [],
        next_actions: ["Schedule post-security demo", "Confirm Q3 vertical launch dates"],
        pipeline_stage: "follow_up",
      },
    },
    {
      id: SEED_IDS.notes.velocityDiscovery,
      meeting_id: SEED_IDS.meetings.velocityDiscovery,
      raw_notes:
        "Publishing 8 blogs/month today, goal is 25. Content team stretched. Head of Content owns SEO roadmap. VP Marketing wants Q2 results. Strong urgency.",
      structured_summary: {
        pain_points: ["Content team overloaded", "SEO output below target"],
        stakeholders: ["Head of Content", "VP Marketing"],
        timeline: "Q2 launch window",
        sentiment: "positive",
        objections: [],
        next_actions: ["Schedule product demo", "Send sample content workflow"],
        pipeline_stage: "follow_up",
      },
    },
    {
      id: SEED_IDS.notes.velocityDemo,
      meeting_id: SEED_IDS.meetings.velocityDemo,
      raw_notes:
        "Demo went well. Main pushback: quality consistency when scaling AI-assisted drafts. Book second demo focused on editorial controls. Demo scheduled for next week.",
      structured_summary: {
        pain_points: ["Quality at scale", "Editorial bottleneck"],
        stakeholders: ["Head of Content", "VP Marketing"],
        timeline: "Decision after follow-up demo",
        sentiment: "positive",
        objections: ["AI content quality concerns"],
        next_actions: ["Second demo focused on QA workflow", "Share SaaS case study"],
        pipeline_stage: "demo_scheduled",
      },
    },
    {
      id: SEED_IDS.notes.relayDiscovery,
      meeting_id: SEED_IDS.meetings.relayDiscovery,
      raw_notes:
        "Paid CAC rising. CMO wants organic to carry more of the funnel. Clear pain and timeline — book demo.",
      structured_summary: {
        pain_points: ["Paid CAC rising"],
        stakeholders: ["CMO", "Head of Growth"],
        sentiment: "positive",
        objections: [],
        next_actions: ["Schedule demo"],
        pipeline_stage: "follow_up",
      },
    },
    {
      id: SEED_IDS.notes.relayDemo,
      meeting_id: SEED_IDS.meetings.relayDemo,
      raw_notes:
        "Demo strong. Agreed to 30-day pilot on blog velocity. Economic buyer engaged.",
      structured_summary: {
        pain_points: ["Need faster blog velocity"],
        stakeholders: ["CMO", "Head of Growth"],
        sentiment: "positive",
        objections: [],
        next_actions: ["Launch pilot", "Schedule closing call"],
        pipeline_stage: "demo_scheduled",
      },
    },
    {
      id: SEED_IDS.notes.relayClosing,
      meeting_id: SEED_IDS.meetings.relayClosing,
      raw_notes:
        "Pilot exceeded traffic target by 18%. Signed annual contract. Deal closed — hand off to customer success.",
      structured_summary: {
        pain_points: [],
        stakeholders: ["CMO", "Head of Growth"],
        sentiment: "positive",
        objections: [],
        next_actions: ["Onboarding handoff to CS"],
        pipeline_stage: "won",
      },
    },
    {
      id: SEED_IDS.notes.searchForgeDiscovery,
      meeting_id: SEED_IDS.meetings.searchForgeDiscovery,
      raw_notes:
        "Founder asked detailed implementation questions — tooling stack, prompt architecture. No clear pain. Competitor research — reject and do not pursue.",
      structured_summary: {
        pain_points: [],
        stakeholders: ["Founder"],
        sentiment: "negative",
        objections: ["Implementation detail fishing"],
        next_actions: ["Mark as reject — do not pursue"],
        pipeline_stage: "rejected",
      },
    },
  ];
}

export function buildManagerInsights() {
  return [
    {
      id: SEED_IDS.insights.metricPulse,
      prospect_id: SEED_IDS.prospects.metricPulse,
      health: "yellow" as const,
      risk: "Early discovery — economic buyer not fully engaged yet.",
      coaching: "Multi-thread to head of content before sending more collateral.",
      pipeline_signal: "First call — inbound pain validated",
      patterns: ["Early stage", "Needs champion expansion"],
    },
    {
      id: SEED_IDS.insights.nomadCommerce,
      prospect_id: SEED_IDS.prospects.nomadCommerce,
      health: "yellow" as const,
      risk: "Multi-vendor eval, CMO absent, no decision date.",
      coaching: "Push for economic buyer meeting and explicit decision timeline.",
      pipeline_signal: "Follow-up — closing call scheduled",
      patterns: ["Shopping behavior", "Missing economic buyer"],
    },
    {
      id: SEED_IDS.insights.stackline,
      prospect_id: SEED_IDS.prospects.stackline,
      health: "yellow" as const,
      risk: "Security cleared — risk shifts to scheduling gap before Q3 launch.",
      coaching: "Book the post-infosec demo this week; loop in content lead on the invite.",
      pipeline_signal: "Follow-up — security cleared, demo not yet scheduled",
      patterns: ["Champion engaged", "Security gate cleared", "Scheduling gap"],
    },
    {
      id: SEED_IDS.insights.velocityHr,
      prospect_id: SEED_IDS.prospects.velocityHr,
      health: "green" as const,
      risk: "Quality objection from last demo — manageable with workflow proof.",
      coaching: "Open the follow-up demo with editorial controls. Ask for pilot commitment.",
      pipeline_signal: "Demo scheduled — strong urgency, Q2 deadline",
      patterns: ["High intent", "Repeat engagement", "Quality objection pattern"],
    },
    {
      id: SEED_IDS.insights.relayCommerce,
      prospect_id: SEED_IDS.prospects.relayCommerce,
      health: "green" as const,
      risk: "None — customer signed.",
      coaching: "Ensure clean CS handoff; capture win story for D2C vertical.",
      pipeline_signal: "Converted — annual contract signed",
      patterns: ["Pilot success", "Fast close", "D2C reference candidate"],
    },
    {
      id: SEED_IDS.insights.searchForge,
      prospect_id: SEED_IDS.prospects.searchForge,
      health: "red" as const,
      risk: "Competitor research signal — agency asking build-level implementation details.",
      coaching: "Deprioritize. Reallocate time to VelocityHR follow-up.",
      pipeline_signal: "Rejected — no further meetings",
      patterns: ["Competitor intel", "No validated pain"],
    },
  ];
}

export function buildJordanMilestones() {
  return [
    { id: "77777777-7777-4777-8777-777777777301", prospect_id: SEED_IDS.prospects.metricPulse, occurred_at: daysAgo(7), label: "First call — inbound pain confirmed", next_step: "Book follow-up with content lead", tone: "neutral" },
    { id: "77777777-7777-4777-8777-777777777111", prospect_id: SEED_IDS.prospects.nomadCommerce, occurred_at: daysAgo(28), label: "Traffic plateau confirmed", next_step: "Run live demo", tone: "neutral" },
    { id: "77777777-7777-4777-8777-777777777112", prospect_id: SEED_IDS.prospects.nomadCommerce, occurred_at: daysAgo(14), label: "Shopping three vendors", next_step: "Get CMO on call", tone: "warning" },
    { id: "77777777-7777-4777-8777-777777777321", prospect_id: SEED_IDS.prospects.stackline, occurred_at: daysAgo(38), label: "Vertical launch pain captured", next_step: "Workflow demo", tone: "positive" },
    { id: "77777777-7777-4777-8777-777777777322", prospect_id: SEED_IDS.prospects.stackline, occurred_at: daysAgo(22), label: "Security review started", next_step: "Complete questionnaire", tone: "warning" },
    { id: "77777777-7777-4777-8777-777777777323", prospect_id: SEED_IDS.prospects.stackline, occurred_at: daysAgo(8), label: "Infosec cleared — schedule demo", next_step: "Book post-security demo", tone: "positive" },
    { id: "77777777-7777-4777-8777-777777777101", prospect_id: SEED_IDS.prospects.velocityHr, occurred_at: daysAgo(24), label: "P0 requirements captured", next_step: "Book product demo", tone: "positive" },
    { id: "77777777-7777-4777-8777-777777777102", prospect_id: SEED_IDS.prospects.velocityHr, occurred_at: daysAgo(11), label: "Raised quality concern", next_step: "Second demo on QA workflow", tone: "warning" },
    { id: "77777777-7777-4777-8777-777777777401", prospect_id: SEED_IDS.prospects.relayCommerce, occurred_at: daysAgo(52), label: "Discovery — CAC pressure", next_step: "Book demo", tone: "positive" },
    { id: "77777777-7777-4777-8777-777777777402", prospect_id: SEED_IDS.prospects.relayCommerce, occurred_at: daysAgo(35), label: "Pilot agreed", next_step: "Run 30-day pilot", tone: "positive" },
    { id: "77777777-7777-4777-8777-777777777403", prospect_id: SEED_IDS.prospects.relayCommerce, occurred_at: daysAgo(9), label: "Annual contract signed", next_step: "CS handoff", tone: "positive" },
    { id: "77777777-7777-4777-8777-777777777121", prospect_id: SEED_IDS.prospects.searchForge, occurred_at: daysAgo(18), label: "Competitor research signal", next_step: "Mark reject", tone: "negative" },
  ];
}
